name: flow_cli
description: A comprehensive Flutter CLI tool for project management, building, and deployment
version: 1.0.0
homepage: https://github.com/Flowstore/flow-cli
repository: https://github.com/Flowstore/flow-cli
issue_tracker: https://github.com/Flowstore/flow-cli/issues
documentation: https://github.com/Flowstore/flow-cli#readme

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.8.3
  io: ^1.0.4
  yaml: ^3.1.2
  http: ^1.1.0
  colorize: ^3.0.0
  interact: ^2.2.0
  process: ^5.0.4
  watcher: ^1.1.0
  logging: ^1.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.3

executables:
  flowtest: main